### ISSUE TITLE
VueRss

### ISSUE THREAD

**Issue by Wattaged** [oeyoews/tiddlywiki-starter-kit#270]
Thanks for nice TW rss plugin! Is it possible to add enclosure url to saved output?
感谢出色的 TW rss 插件！是否可以将附件 URL 添加到已保存的输出中？

**Comment by oeyoews** [comment]
![image](https://github.com/oeyoews/tiddlywiki-starter-kit/assets/72405338/f069c9a9-e220-4428-a0a6-363102be59f0)
By default there will be a generated link field for the saved tiddler. If this is what you want, you can write your own template to render this field.

**Comment by Wattaged** [comment]
Thank you for the quick reply. I can see the existing title link but I would also like to include a link to the enclosure tag > url attribute,  if it exists (for podcasts etc).

Here is an example RSS feed that has the enclosure tag with the url attribute;

https://feeds.megaphone.fm/hubermanlab

As an example, Chatgpt suggested something like this. I can't get it to work in your app.js but it helps explain;

```       
          // Check if <enclosure> exists
          if (enclosure) {
            // Access enclosure URL
            const enclosureUrl = enclosure.getAttribute('url');
            
            // Add enclosure URL to the array
            this.enclosureUrls.push(enclosureUrl);

```

I hope this explains more clearly. It isn''t really an issue, more of an enhancement. The plugin is already very useful, thanks.

**Comment by oeyoews** [comment]
I get it, I'm going to support this

**Comment by Wattaged** [comment]
Thank you oeyoews.

**Comment by oeyoews** [comment]
![image](https://github.com/oeyoews/tiddlywiki-starter-kit/assets/72405338/89afa989-6a32-441c-968f-46890c459645)

**Comment by oeyoews** [comment]
The mp3 has not been put into tiddler yet, it will be processed later.

**Comment by Wattaged** [comment]
Great. It works well with mp3 but please note not all enclosures are mp3. Example here;

https://peertube.dair-institute.org/feeds/podcast/videos.xml?videoChannelId=11

Maybe just including the enclosure link in the saved item tiddler would be enough. TW user can then decide how to handle any different filetypes enclosed. Less complicated for you. Enclosure could be audio, video or stream playlist like above. 
Thanks again for this feature - it works very well for most audio podcasts as it is.

**Comment by Wattaged** [comment]
Very nice and useful feature - thank you!
